### ISSUE TITLE
django-mongodb-engine and django-rest-framework-mongoengine

### ISSUE THREAD

**Issue by ikeralbeniz** [umutbozkurt/django-rest-framework-mongoengine#104]
When i use django.db.models.Model like in django-mongodb-engine

http://django-mongodb-engine.readthedocs.org/en/latest/tutorial.html

when i try to use django-rest-framework-mongoengine i get this error:

> type object 'Video' has no attribute 'id'

En example object stored on DB

```javascript
{
    "_id": {
        "$oid": "5564d0c8424f7704aea99813"
    },
    "user_id": {
        "$oid": "5564c86e424f777f81d8f3ec"
    },
    "description": "https://www.youtube.com/watch?v=4cpXdFcaLVg",
    "videoid": "4cpXdFcaLVg",
    "source": "YT",
    "location": {
        "lat": 38.992877,
        "lon": 1.289047
    },
    "pub_date": {
        "$date": "2015-05-26T13:51:25.000Z"
    },
    "name": "Gracioneta"
}
```

is django-mongodb-engine compatible with django-rest-framework-mongoengine??

**Comment by qwiglydee** [comment]
django-rest-framework-mongoengine uses and relies on mongoengine.
django-mongodb-engine is quite another mongo engine for quite another django (nonrel fork)
