### ISSUE TITLE
AttributeError at /users/

### ISSUE THREAD

**Issue by togaPaulo** [umutbozkurt/django-rest-framework-mongoengine#105]
try run server from example and i have error:

'UserSerializer' object has no attribute '_include_additional_options'

**Comment by adil-abbasi-10p** [comment]
+1 I am having the same issue.

**Comment by togaPaulo** [comment]
I use serializers of django-rest-framework for serializer my documents of mongoengine, it works perfect

**Comment by qwiglydee** [comment]
duplicate of #110
