### ISSUE TITLE
Serializer' object has no attribute '_include_additional_options'

### ISSUE THREAD

**Issue by shoaib-ijaz** [umutbozkurt/django-rest-framework-mongoengine#110]
I have created a sample app.When i tried to call any URL then I found following error.

'ComplaintSerializer' object has no attribute '_include_additional_options'

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/list/

Django Version: 1.7
Python Version: 3.4.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'g',
 'rest_framework',
 'rest_framework_mongoengine')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "C:\Python34\lib\site-packages\rest_framework\viewsets.py" in view
  85.             return self.dispatch(request, *args, **kwargs)
File "C:\Python34\lib\site-packages\rest_framework\views.py" in dispatch
  456.             response = self.handle_exception(exc)
File "C:\Python34\lib\site-packages\rest_framework\views.py" in dispatch
  453.             response = handler(request, *args, **kwargs)
File "C:\Python34\lib\site-packages\rest_framework\mixins.py" in list
  44.             return self.get_paginated_response(serializer.data)
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in data
  622.         ret = super(ListSerializer, self).data
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in data
  217.                 self._data = self.to_representation(self.instance)
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in to_representation
  572.             self.child.to_representation(item) for item in iterable
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in <listcomp>
  572.             self.child.to_representation(item) for item in iterable
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in to_representation
  426.         fields = [field for field in self.fields.values() if not field.write_only]
File "C:\Python34\lib\site-packages\rest_framework\serializers.py" in fields
  317.             for key, value in self.get_fields().items():
File "C:\Python34\lib\site-packages\rest_framework_mongoengine\serializers.py" in get_fields
  198.         extra_kwargs = self._include_additional_options(extra_kwargs)

Exception Type: AttributeError at /list/
Exception Value: 'ComplaintSerializer' object has no attribute '_include_additional_options'

**Comment by shoaib-ijaz** [comment]
For testing purpose I have changed Line13:

#extra_kwargs = self._include_additional_options(extra_kwargs)
extra_kwargs = self.get_extra_kwargs()

Now I am facing another error :)

'ComplaintSerializer' object has no attribute '_get_default_field_names'

This error Line:206
fields = self._get_default_field_names(declared_fields, info) 

I have also changed this one line too. :bow: 

fields = self.get_default_field_names(declared_fields, info) 

After these two modifications, I have executed again same URL

Oh yes I can see now my result. :dancer:

**Comment by malderete** [comment]
@shoaib-ijaz Im having the same issue, I've made the change you proposed and it worked, Thanks!
It looks like the project is using the wrong API. My worry is the state of the project, does somebody know it?
thanks in advance

**Comment by qwiglydee** [comment]
This should be gone in current trunk.
Check against it.

**Comment by qwiglydee** [comment]
not an issue with current code
