### ISSUE TITLE
ObjectId field's 'to_internal_value' uses 'unicode' function - throws exception in Py3

### ISSUE THREAD

**Issue by optik** [umutbozkurt/django-rest-framework-mongoengine#120]
As in the subject - the following code is not Python 3 compatible and will throw a 'unicode is not defined' exception. Furthermore, this exception does not have a 'message' property which makes the entire except block fall flat.

    def to_internal_value(self, data):
        try:
            return ObjectId(unicode(data))
        except Exception as e:
            raise serializers.ValidationError(e.message)

**Comment by qwiglydee** [comment]
fixed in master
