### ISSUE TITLE
Support use case with new obj creation at ReferenceField

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#133]
Framework should support use case: "select an object from existent, or create new"

Serializer should support customized ReferenceField with behaviour:
* rendering as id or nested object as usual, according to depth value of serializer
* parsing as id or nested object, according to provided data
  * id is converted to DBRef or ObjectId, according to dbref parameter of ReferenceField
  * nested object is delegated to handle to `serializer.create` or `serializer.update`

**Comment by qwiglydee** [comment]
Or, maybe, it is still possible with just custom nested serializer...

**Comment by erback** [comment]
What is the current status on this feature? Is there are recommended workaround? I currently get a 
"Cannot parse "12" as ObjectIdField."' when I'm passing a reference to another document collection (the reference is the ID as an INT). But maybe I'm just doing it wrong?

 Thanks for the help!

**Comment by qwiglydee** [comment]
Using int instead of objectid is another issue #145 and I believe is solved, but I missed to put it into docs.
you need:
```python
class IntReferenceField(ReferenceField):
    pk_field_class = rest_framework.fields.IntegerField
```

**Comment by qwiglydee** [comment]
As for this issue, I still have no solution. But I will soon, because I need it in my project.

**Comment by erback** [comment]
Thanks for the quick response. Tried the above without success which leads me to think that I'm doing some sort of newbie mistake and shouldn't have this issue from the start.

**Comment by erback** [comment]
I read the following in the documentation:

"If your docments have another type for ids, you need to create custom ReferenceField subclass and override this atribute to corresponding serializer field. However, this custom ReferenceField subclass will not be used automagically by DocumentSerializer, and you have to declare fields manually."

Would it be possible to get an example of how this would be use.

from rest_framework_mongoengine.serializers import DocumentSerializer, EmbeddedDocumentSerializer
from application.models import *
from mongoengine import *

class IntReferenceField(ReferenceField):
    pk_field_class = fields.IntegerField()


class StepSerializer(DocumentSerializer):
	parent = IntReferenceField("Step")
	class Meta:
		model = Step
		depth = 0

**Comment by qwiglydee** [comment]
@erback 
the pk_field_class should be a class, not an instance
the model argument of ReferenceField should be a document class, not a string

**Comment by qwiglydee** [comment]
@erback also,
when you use `import *` - nobody (including yourself) can not understand where you symbols come from. 
in this case, `fields` is probably imported from mongoengine (according to import) instead of serializers, which is competely wrong usage of ReferenceField

**Comment by erback** [comment]
@qwiglydee Thanks, it works like a charm! Sorry for the sloppiness... Really appreciate your work!
