### ISSUE TITLE
OrderedDict missing

### ISSUE THREAD

**Issue by Glueon** [umutbozkurt/django-rest-framework-mongoengine#134]
Hi. I tried to use your serializer with the latest django rest framework. 

So I get such an error:
```
  File "/usr/local/lib/python3.4/site-packages/rest_framework_mongoengine/utils.py", line 8, in <module>
    from rest_framework.compat import OrderedDict
ImportError: cannot import name 'OrderedDict'
```

It seems that  `OrderedDict`  was removed from `from rest_framework.compat` because of python3. So I guess you need to add a `try ... catch` statement and try to import it from `collections` in case of python 3.

There is even a PR but it simply tries to take `OrderedDict` from the `collections`. Maybe that's not what you want.

**Comment by qwiglydee** [comment]
fixed in master
