### ISSUE TITLE
Implement GeoFields with validation and stuff

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#139]
```class BaseGeoField(serializers.Field):
    default_error_messages = {
        'invalid_keys': "Value should be dictionary with keys 'type' and 'coordinates'",
        'invalid_geotype': "Incorrect geometry type",
        'invalid_floats': "Incorrect coordinate value",
        'invalid_coords': "Incorrect number of coordinates"
    }
    valid_types = ('Point', 'MultiPoint', 'LineString', 'MultiLineString', 'Polygon', 'MultiPolygon')
```

TODO: MultiPoint, MultiLine, MultiPoly

**Comment by sudhakso** [comment]
While I use GeoPointField in mongo, I get a key error in DRF. Can you please fix it or suggest me an alternative.

**Comment by qwiglydee** [comment]
@sudhakso you mean the very GeoPointField, the obsolete 2d-coordinates? 
Not PointFields with new spherical coordinates?

**Comment by sudhakso** [comment]
I can change it to refer to pointfield. But from drf source code, I could
see a commit removing geo related fields.

I am little worried 'cz our application design relies on them and we are
going to hit the market soon.

Do you have a plan to implement  support for PointField.

**Comment by qwiglydee** [comment]
Upcoming release will have all GeoFields included back.

**Comment by sudhakso** [comment]
Thanks. When is the first cut of the release available for the consumers?

**Comment by bsmartt13** [comment]
qwiglydee thanks so much for your efforts.  I am blocked from upgrading DRF, mongoengine until someone puts in some time here, so I appreciate that.

**Comment by qwiglydee** [comment]
TODO plan:

* GeoPointField -- for 2D point
 * internal/presentation: [float, float]
 * validation: delegate to underlying model_field
 * map to GeoPointField

* GeoField -- field for all spherical fields 
 * init kwarg geo_type == geometry type
 * value: [ coords ]
 * input: [ coords ] or { type: str, coordinates: [ coords ] }, copy coords w/out parsing/validation
 * validation: check toplevel type, .type attribute, delegate to underlying model_field
 * presentation: { type: str, coordinates: [ coords ] }
 * map to all GeoJsonBaseFields with kwarg[geo_type] = model_field._type

* ask mongoengine devs for generic Geometry field
