### ISSUE TITLE
do something with GenericEmbeddedDocument

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#140]
probably fallback to DocumentField

**Comment by qwiglydee** [comment]
It should produce and handle `_cls` attribute just like underlying model field.

**Comment by yogeshpatel** [comment]
Hi plas keep posted when Serializer for GenericEmbeddedDocumentField is available.
if  there is alternate to use  GenericEmbeddedDocumentField please let me know
THx

**Comment by qwiglydee** [comment]
@yogeshpatel i'm going to make serialization with additional attribute "_cls" with class name, the same way as it's used by mongoengine to store generic docs in db.

Will such implementaion satisfy your use case?

**Comment by yogeshpatel** [comment]
@qwiglydee Thanks for update.
