### ISSUE TITLE
New ReferenceField not working in Python 2.7

### ISSUE THREAD

**Issue by dslamba** [umutbozkurt/django-rest-framework-mongoengine#144]
The init method of the new implementation of reference field calls:
          super().__init__(**kwargs)

This is invalid in python 2.7 which expects super to be called with the parent class name

**Comment by qwiglydee** [comment]
A lot of stuff not working in py27 (18 out of 38 tests).
I will address this issue this weekend, before moving any further.
Config to run tests in both 2.7 and 3.4 is already set up.
