### ISSUE TITLE
non-objectid references not supported

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#145]
sometimes happen

**Comment by TonyPythoneer** [comment]
What is the issue?

**Comment by qwiglydee** [comment]
@TonyPythoneer 
The `_id` of objects is not necessary ObjectId. It could be any type.
For instance, if you import openstreetmap data  - it has integer identifiers.
I'm just not sure everything will work in such cases.
