### ISSUE TITLE
When do you release the newest version?

### ISSUE THREAD

**Issue by TonyPythoneer** [umutbozkurt/django-rest-framework-mongoengine#146]
Hello

I was using `django-rest-framework-mongoengine==2.0.2` to do something. But I encountered a bug:

```
cannot import name OrderedDict
Request Method:	POST
Request URL:	http://127.0.0.1:8000/api/users/login
Django Version:	1.8.5
Exception Type:	ImportError
Exception Value:	
cannot import name OrderedDict
Exception Location:	D:\INSTALL\Python\lib\site-packages\rest_framework_mongoengine\utils.py in <module>, line 8
```

I tried to track the source code in `rest_framework_mongoengine\utils.py` and I found this code line `from rest_framework.compat import OrderedDict` is the main bug cause. The reason is `rest_framework` hasn't this function, so it definely returned the issue.

Now, I re-download the newest version(2.1.0) from your github, not pip (https://pypi.python.org/pypi/django-rest-framework-mongoengine/2.0.2). I has checked the `utils.py` it hasn't the issue.

Please release fixed version on pip. I believe other developer has same confused. Thanks.

**Comment by qwiglydee** [comment]
Release is planned to be at end of November
https://github.com/umutbozkurt/django-rest-framework-mongoengine/milestones

I believe I close all remaining issues (marked "3.x") during this week.

**Comment by TonyPythoneer** [comment]
Thanks your answer.

I expect your the newest release.

**Comment by mp3por** [comment]
The latest version on pip is still 2.0.2 ? I encountered the same bug as this one.

**Comment by TonyPythoneer** [comment]
@mp3por 

I have two solution about it:

# Download from github, not from pip.

My django-rest-framework-mongoengine version is `2.1.0`. It download from github source code. The author has the newest version on this repository.

So don't use pip to download it, its the newest version is `2.0.2`. It has some unknown bug.

# degrade relative libraries

This is my relative libraries list:

```
djangorestframework==3.0.5
django-rest-framework-mongoengine==2.0.2
pymongo==2.8
mongoengine==0.9.0
```

It can avoid some issue.
