### ISSUE TITLE
Support for MapField

### ISSUE THREAD

**Issue by RollingFred** [umutbozkurt/django-rest-framework-mongoengine#158]
I have a problem with this model:

```python
class K(EmbeddedDocument):
    name = StringField()

class Record(Document):
    c = DictField()
    ks = MapField(ListField(EmbeddedDocumentField(K)))
```
All works well in MongoEngine and I have documents like:
```
{
    'c': { 'name': 'test'},
    'ks': {
        'Name1': [
            { 'name': 'Name1' }
        ]
}
```

Trying to have a REST call GET on this collection leads to:

```
KeyError: "<class 'mongoengine.fields.MapField'> is not supported, yet. 
Please open a ticket regarding this issue and have it fixed asap.\n
https://github.com/umutbozkurt/django-rest-framework-mongoengine/issues/"
```

Here I am :-)

Note that I have other Models (not using MapField) and their REST api calls works perfect. Thanks for that.
Any help is appreciated.

**Comment by qwiglydee** [comment]
This relates to old drf_2 branch.
Current release support almost everything.

**Comment by RollingFred** [comment]
Nevermind. I was trusting what was installed in our project.
Upgraded and all is fine.
Thanks!
