### ISSUE TITLE
make new release

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#162]
Test framework "in vivo".
Update and publish docs.
Clean up comments.

**Comment by BurkovBA** [comment]
@qwiglydee Maxim, I think, we need a new release. Current PyPI package is broken and people our complaining about it and leaving the project, while they could've become potential users and contributors. Please, create a release just for PyPI users to have a working version - without updating docs and comments. Or tell me, what to do and I'll do that.

**Comment by qwiglydee** [comment]
Yes. I'll manage that soon.

**Comment by BurkovBA** [comment]
Done.
