### ISSUE TITLE
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the NestedSerializer serializer.

### ISSUE THREAD

**Issue by amirasaran** [umutbozkurt/django-rest-framework-mongoengine#196]
I just updated `django-rest-framework` to `3.5.*`, and i got this error 

```
    Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the NestedSerializer serializer.
```

my serializers defines as bellow:

```
class FlightResponseSerializer(mongo_serializer.EmbeddedDocumentSerializer):
    class Meta:
        model = models.FlightModelList
        exclude = ('request_id', 'application', 'provider')
        depth = 3


class SearchGetOutputSerializer(mongo_serializer.EmbeddedDocumentSerializer):
    request_id = serializers.CharField()
    available_flights = FlightResponseSerializer(many=True)

    class Meta:
        model = models.FlightResponse
        fields = ('request_id', 'last_seed', 'available_flights')

```

**Comment by BurkovBA** [comment]
Hi, @amirasaran!

You shouldn't create two serializers manually. Instead, do it as follows:

```
class FlightResponse(mongoengine.Document):
     ...

class SearchGetOutput(mongoengine.Document):
    request_id = mongoengine.StringField(required=True, primary_key=True)
    available_flights = EmbeddedDocumenListField(FlightResponse)


class SearchGetOutputSerializer(mongo_serializer.DocumentSerializer):
    class Meta:
        model = models.SearchGetOutput
        depth = 3

```

I mean, in DRF-ME you don't create nested serializers for EmbeddedDocuments manually. You just declare `EmbeddedDocumentField` or `EmbeddedDocumentListField` on your Document model and create top-level serializer only for that top-level Document. DRF-ME will create all the EmbeddedDocumentSerializers automatically.

**Comment by amirasaran** [comment]
Thanks @BurkovBA 
I got your concept, but DRF-ME should support the latest version of DRF.

do you have any idea about this ?

**Comment by BurkovBA** [comment]
@amirasaran
Yeah, you're right about the release. There's a lot of unreleased changes in DRF-ME, which are compatible with DRF 3.3.3, so I'll make a release for DRF 3.3.3 first and then look into new features in DRFs 3.4 and 3.5.

**Comment by chepe4pi** [comment]
I create a pull request

**Comment by amirasaran** [comment]
@chepe4pi  Thanks 

when we can use this changes via `pip` ?

**Comment by chepe4pi** [comment]
@amirasaran I'm not sure about it...
@BurkovBA Can you answer?

**Comment by BurkovBA** [comment]
@chepe4pi @amirasaran  I have maintainer permissions here at github, but to create a PyPI release, I need Umut Bozkurt to give mу maintainer permissions at PyPI. I've sent a request to him, currently waiting for him to answer. After that, I hope, I make a release the next weekend.

**Comment by BurkovBA** [comment]
@chepe4pi @amirasaran Umut gave me maintainer permissions at PyPI. I hope, I'll release 3.3.1 at this weekend.

**Comment by BurkovBA** [comment]
Released 3.3.1 at least for python2.7.

**Comment by Ansh0123** [comment]
for me it worked as the error is saying fields .....
class FlightResponseSerializer(mongo_serializer.EmbeddedDocumentSerializer):
    class Meta:
        model = models.FlightModelList
        exclude = ('request_id', 'application', 'provider')
        depth = 3
        fields = '__all__'  #This should work :)

**Comment by ola-t** [comment]
I think it is fields=‘__all__’

**Comment by duydp** [comment]
I'm facing with this error, who can help me now? thanks for your helping.

Hayzz 2 minutes I resolved it =>add 
fields = '_ _ all _ _' 
here (that's very simply)

**Comment by IATF** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
