### ISSUE TITLE
'tuple' object has no attribute 'lower'

### ISSUE THREAD

**Issue by hanx11** [umutbozkurt/django-rest-framework-mongoengine#197]
I have DateTimeField in the document, when i serializer this field, i encounter """'tuple' object has no attribute 'lower'"" error!

**Comment by BurkovBA** [comment]
Thanks for reporting! Will try to reproduce.

**Comment by BurkovBA** [comment]
@hanx11 Can you give a code example of what you do? DateTimeField is covered with unit-tests well enough, so I don't see, what could be wrong with it.

**Comment by hanx11** [comment]
Thanks all! it's my fault. In my project's settings, i set "DATETIME_FORMAT" to be a tuple.

**Comment by hanx11** [comment]
@BurkovBA Thank you very much! It's my fault. In my project's settings, i set "DATETIME_FORMAT" to be a tuple incorrectly.
