### ISSUE TITLE
mistake in class name in docs

### ISSUE THREAD

**Issue by chepe4pi** [umutbozkurt/django-rest-framework-mongoengine#198]
http://umutbozkurt.github.io/django-rest-framework-mongoengine/viewsets.html#rest_framework_mongoengine.viewsets.GenericViewSet

correct name - MongoGenericViewSet

**Comment by qwiglydee** [comment]
Nope.
I converted all class names to exactly match those of DRF, because they should provide identical interface, and DRF documentation can be referenced.
Classes with prefix Mongo implement some specific mongo-related features.

It's kinda design decision.

**Comment by chepe4pi** [comment]
Ok. Thanks a lot!

**Comment by chepe4pi** [comment]
It's ok. It fixed just after I upgrade django-rest-framework-mongoengine to 3.3.0
