### ISSUE TITLE
ImportError: No module named Sample.settings

### ISSUE THREAD

**Issue by KiranPrajapati345** [umutbozkurt/django-rest-framework-mongoengine#200]
When I use python manage.py runserver  then  its gives me error "ImportError: No module named Sample.settings"

I have first download "django-rest-framework-mongoengine-master" and unzip file, then  next i install all requirement packages (pytest ......isort ) , next I use  ./runtests.py --fast  this command... and next I use python manage.py runserver.

So, where is Sample.settings?  I want to connect my database  (stored in mongo) using mongoengine.
and show data output and complex queries in django-rest-framework  , I am confuse, how to connect database?

**Comment by BurkovBA** [comment]
@KiranPrajapati345  Hi! What are you trying to achieve? Do you want to use DRF-Mongoengine in your project or do you want to contribute to DRF-Mongoengine?

If you want to use DRF-ME in your project, just say `pip install django-rest-framework-mongoengine` and you need all the dependencies from our requirements.txt installed (`django`, `mongoengine`, `drf` and `blinker`) - this can be done with `pip install -r requirements.txt`. Then you can use `DocumentSerializers` from it in your `serializers.py` and `Router` in `urls.py`. 

If you want to contribute to DRF-ME, you just clone DRF-ME from github and then install testing  requirements from `requirements/requirements-testing.txt`. Then you run `.runtests.py` script, which runs all tests, using `tox` and `pytest`.

**Comment by KiranPrajapati345** [comment]
Hello sir,

I want to create a REST API that returns value of some data from mongodb
with django.
I used that  requirements.txt  and install all packages but next what  I
add for connect my mongodb database

my data is in mongodb (KIRAN database)  please find attachment (data.png) .
 I want to show this data in  django-rest-api sever.
so I  have install django-rest-framework-mongoengine and all packages like
(blinker, pytest .pytest-cov, pytest-django,pep8..etc)

and I run python runtest.py file and gives  flake8 error, I solve that
error . next when I use python manage.py runserver its gives me error " No
module name "sample.settings ."


how to I connet my db database in djagno-restframework-mongoengine ?

can you please help me, how I got my data using
djago-restframework-mongoengine  when my data is stored in mongo?

Thanks and regards,
Kiran Prajapati

**Comment by BurkovBA** [comment]
@KiranPrajapati345

Ok, so you want to use DRF-Mongoengine for your project, not contribute to it. In such case, you don't need developer's dependencies, such as `pytest`, `pytest-cov`, `pytest-django`, `pep8` etc.

You need only `django`, `django-rest-framework`, `mongoengine` and `django-rest-framework-mongoengine`. So, you just install them as follows:

```
pip install django djangorestframework mongoengine django-rest-framework-mongoengine
```

I don't really have time to explain, how to set up django and django-rest-framework in full detail, but I'll give you a short instruction. You need to:

- create a django project and a django app with `django-admin startproject <your project's name>`, `django-admin startapp <your app's name>`
- edit the `settings.py` file of your projects: add `rest_framework` and `rest_framework_mongoengine` to `INSTALLED_APPS` variable and set up connection to mongo like this:

```
MONGODB_DATABASES = {
    "default": {
        "name": "universe",
        "host": "workflows-mongo",
        "port": 27017,
        "tz_aware": True,  # if you use timezones in django (USE_TZ = True)
    },

    "test": {
        "name": "test_universe",
        "host": "workflows-mongo",
        "port": 27017,
        "tz_aware": True,  # if you use timezones in django (USE_TZ = True)
    }
}

    mongoengine.connect(
        db=MONGODB_DATABASES[db]['name'],
        # TODO: username=MONGO_DATABASES['default']['username'],
        # TODO: password=MONGO_DATABASES['default']['password'],
        host=MONGODB_DATABASES['default']['host']
    )
```

Now, how to write your API in drf-mongoengine? You can read [the official documentation](http://umutbozkurt.github.io/django-rest-framework-mongoengine/) and [this article](https://medium.com/@vasjaforutube/django-mongodb-django-rest-framework-mongoengine-ee4eb5857b9a) for primer.

**Comment by BurkovBA** [comment]
@KiranPrajapati345

As for the error:

```
mongoengine.connect(db="Tools",host="localhost")
NameError: name 'mongoengine' is not defined
```

You just haven't imported the `mongoengine` module. Add `import mongoengine` to the beginning of your `settings.py`. 

I've also created an example project, using `drf-monogoengine` for you. Here it is: https://github.com/BurkovBA/django-rest-framework-mongoengine-example. Ask me, if you don't understand something in it.

**Comment by KiranPrajapati345** [comment]
Hello sir,

Thanks you so much sir,
Its  works. Happy to run this server finally :)

But can you just  attach data   that's you are stored in mongodb "
project"  db (database) ?
Because I have no idea which data is stored in  your project db?
and in settings.py file

mongoengine.connect(
    db=MONGODB_DATABASES[db]['name'],
    host=MONGODB_DATABASES[db]['host']
)


I need to include database name ['project'] instead of  ['name']  here?

db = MONGODB_DATABASES[db]['project']
host  =MONGODB_DATABASES[db]['host']

 please see screen shot (doubt.png)

and once we run  http://127.0.0.1:8000/api/tool

how to see our data that we are stored in 'project' collection instead of
create data?

for example : in mongodb    [test db] I stored my data in collection
[KIRAN31] .
and if we use mongo shell , db.KIRAN31.find()     our collection data is
shows in mongo shell
please see screenshot (Doubt2.png)
and  using mongoengine I want to show in  djnago server
please see screen shot ( wbcis data.png)

Thanks and regards,
Kiran Prajapati

**Comment by BurkovBA** [comment]
@KiranPrajapati345 

Ok, here's an example of data, stored in Tool collection. You can paste it into "raw data" view of your Browsable API and it will be stored in your database:

```
{
    "_id" : "Soapfuse",
    "class" : "CommandLineTool",
    "label" : "Soapfuse",
    "description" : "",
    "owner" : [ 
        "10"
    ],
    "contributor" : [],
    "inputs" : [ 
        {
            "id" : "#displayName",
            "label" : "JobName",
            "description" : "SomeId to code sample",
            "type" : [ 
                "string"
            ],
            "inputBinding" : {
                "position" : 1
            },
            "required" : true
        }, 
        {
            "id" : "#readsFile1",
            "label" : "readsFile2",
            "description" : "Fastq left reads",
            "type" : [ 
                "File"
            ],
            "inputBinding" : {
                "position" : 2
            },
            "required" : true
        }, 
        {
            "id" : "#readsFile2",
            "label" : "ReadsFile2",
            "description" : "Fastq right reads",
            "type" : [ 
                "File"
            ],
            "inputBinding" : {
                "position" : 3
            },
            "required" : true
        }, 
        {
            "id" : "#fileFormat",
            "label" : "",
            "description" : "",
            "type" : [ 
                {
                    "symbols" : [ 
                        "fq", 
                        "fq.gz", 
                        "fastq"
                    ],
                    "type" : "enum",
                    "name" : "allowedFileFormats"
                }
            ],
            "inputBinding" : {
                "position" : 4
            },
            "required" : true
        }, 
        {
            "id" : "#reference",
            "label" : "reference",
            "description" : "Reference for soapfuse",
            "type" : [ 
                "File"
            ],
            "inputBinding" : {
                "position" : 5
            },
            "required" : true
        }, 
        {
            "id" : "#insertSize",
            "label" : "",
            "description" : "",
            "type" : [ 
                "null", 
                "int"
            ],
            "inputBinding" : {
                "position" : 7
            },
            "required" : true
        }, 
        {
            "id" : "#intronSearch",
            "label" : "",
            "description" : "",
            "type" : [ 
                "null", 
                "int"
            ],
            "inputBinding" : {
                "position" : 8
            },
            "required" : true
        }
    ],
    "outputs" : [ 
        {
            "id" : "#outputFile",
            "type" : [ 
                "File"
            ],
            "outputBinding" : {
                "glob" : "result.soapfuse.tgz"
            },
            "required" : true
        }
    ],
    "baseCommand" : [ 
        "/workdir/run_soapfuse.sh"
    ],
    "arguments" : [ 
        {
            "position" : 6,
            "valueFrom" : "result.soapfuse.tgz"
        }
    ],
    "requirements" : [ 
        {
            "dockerPull" : "avkitex/soapfuse:latest",
            "class" : "DockerRequirement"
        }, 
        {
            "coresMin" : "4",
            "ramMin" : "15000",
            "class" : "ResourceRequirement",
            "outdirMin" : "50000",
            "tmpdirMin" : "100000"
        }
    ],
    "hints" : [ 
        {
            "defaultReferenceHint" : "first",
            "listReferencesFor" : [ 
                {
                    "referenceForTools" : [ 
                        "SOAPfuse-v1.26"
                    ],
                    "id" : "reference"
                }
            ],
            "class" : "bg:ReferenceEncode"
        }
    ],
    "successCodes" : [],
    "temporaryFailCodes" : [],
    "permanentFailCodes" : []
}
```

**Comment by KiranPrajapati345** [comment]
Hello sir, I got it ..! :)

In  setting.py

# We define 2 Mongo databases - default and test
MONGODB_DATABASES = {
    "default": {
        "name": "Rabbi",
        "host": "localhost",
        "port": 27017,
        "tz_aware": True,  # if you use timezones in django (USE_TZ = True)
    },

I have use  where I data stored in mongodb.
So, my db is Rabbi and collection is  "tool"
and it's works.  Awesome code..!!

Thank you so much sir.

Thanks and regards,
Kiran Prajapati

**Comment by KiranPrajapati345** [comment]
Hello sir,

Is there any way to writing  queries for multiple fields using mongoengine?
I want to writing  a query  for   Fruit =Guava in Revenue_circle
=urlikanchan  and   also writing a query for
how many number of fruits are made in pune district,  nasik district .. etc?

we need to write queries in models.py file?


Please find attahcment


On Mon, Dec 5, 2016 at 1:35 PM, Kiran Prajapati <prajapati.kiran28@gmail.com

**Comment by BurkovBA** [comment]
@KiranPrajapati345 

Unfortunately, I didn't find any attachments in your e-mails. May be GitHub blocks them?

Django REST Framework doesn't support multiple id fields as yet. So, you cannot have a REST api endpoint e.g. `/api/district/<nasik>/fruit/<guava>/` out of the box.

But, you can use [filtering in DRF](http://www.django-rest-framework.org/api-guide/filtering/), which is supported out of the box. You need to override your APIView or APIViewSet to use this functionality. 

Sorry, I don't have time to help you with the details about how to use standard DRF due to my full-time job. You'll have to familiarize yourself with [the documentation of standard DRF](http://www.django-rest-framework.org/) first. And then, when you try using DRF-Mongoengine, you can find [many helpful examples in the unit-tests](https://github.com/umutbozkurt/django-rest-framework-mongoengine/tree/master/tests) of DRF-Mongoengine.

Good luck!

**Comment by KiranPrajapati345** [comment]
Thanks you sir,

you are helped me already so much.

Thanks a lot.

**Comment by KiranPrajapati345** [comment]
Hi,
i don't know if is the right place to ask, because it's not an issue, just a question.

I'm using rest_framework_mongoengine to build APIs for my app 
I would like to know if there's a way to get this filter working

http://api/tool/?crop=banana,guava

to get all crop "banana OR crop "guava".

I've tried with

http://api/tool/?crop=guava&category=banana

but as expected it does an AND between the filters and retrieve only the banana crop (i suppose because it's the last filter).
I am not sure which packages need to import using rest_framework_mongoengine
Here is my views.py file:

from __future__ import unicode_literals

from django.template.response import TemplateResponse

from rest_framework_mongoengine.viewsets import ModelViewSet as MongoModelViewSet

from app.serializers import *


def index_view(request):
    context = {}
    return TemplateResponse(request, 'index.html', context)


class ToolViewSet(MongoModelViewSet):
    serializer_class = ToolSerializer
    my_filter_fields = ('crop', 'district','taluka','circle','year',) # specify the fields on which you want to filter

    def get_kwargs_for_filtering(self):
        filtering_kwargs = {} 
        for field in  self.my_filter_fields: # iterate over the filter fields
            field_value = self.request.query_params.get(field) # get the value of a field from request query parameter
            if field_value: 
                filtering_kwargs[field] = field_value
        return filtering_kwargs 

    def get_queryset(self):
        queryset = Tool.objects.all() 
        filtering_kwargs = self.get_kwargs_for_filtering() # get the fields with values for filtering 
        if filtering_kwargs:
            queryset = Tool.objects.filter(**filtering_kwargs) # filter the queryset based on 'filtering_kwargs'
        return queryset

This code is work for "And" query .
http://api/tool/?crop=guava&taluka=haveli
http://api/tool/?district=pune&taluka=haveli
etc gives correct output,

Now, I want to write query for "OR" query,
I know how to works  this  using django-filters

here is my code : 
from rest_framework import generics,filters
from rest_framework.filters import SearchFilter
from django_filters import Filter,CharFilter
from django_filters.fields import Lookup

class ListFilter(CharFilter):

    def sanitize(self, value_list):
        """
        remove empty items in case of ?number=1,,2
        """
        return [v for v in value_list if v != u'']

    def customize(self, value):
        return value

    def filter(self, qs, value):
        multiple_vals = value.split(u",")
        multiple_vals = self.sanitize(multiple_vals)
        multiple_vals = map(self.customize, multiple_vals)
        actual_filter = django_filters.fields.Lookup(multiple_vals, 'in')
        return super(ListFilter, self).filter(qs, actual_filter)

class ListIntegerFilter(ListFilter):

    def customize(self, value):
        return int(value)

class ToolViewSet(ModelViewSet):
    queryset = Toolobjects.all()
    model=Tool
    serializer_class = ToolSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,SearchFilter,filters.OrderingFilter,)
    filter_class = ToolFilterSet

but this code is works in django-filter, not working in rest-framework-mongoengine

So,can you please help me for how to write this code in rest-framework-mongoengine ? what i have to import in views.py file ?

**Comment by BurkovBA** [comment]
This turned to be a discussion instead of a question. Closing
