### ISSUE TITLE
Validated_data has OrderedDict instead of EmbeddedDocument object

### ISSUE THREAD

**Issue by ShipraShalini** [umutbozkurt/django-rest-framework-mongoengine#202]
I just updated django-rest-framework-mongoengine to v3.3.1.
I am using DocumentSerializer with ModelViewSet. Earlier, the validated_data had embedded documents object but now all the embedded documents are OrderedDict.

Do I need to change my code or is it a bug?

**Comment by BurkovBA** [comment]
@ShipraShalini

Hi, Shipra!

Yes, this isn't a bug, this is an intentional change of the implementation of [DocumentSerializer.to_internal_value()](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L187) to keep validated_data an OrderedDict and not clutter it with EmbeddedDocuments. Now each EmbeddedDocumentSerializer also receives _validated_data attribute with sub-json and walks through it. Sorry that it breaks your code.

**Comment by ShipraShalini** [comment]
@BurkovBA My whole project is based around django-rest-framework-mongoengine 3.3.0, is there any way I can get the object like behaviour from embedded documents?

**Comment by BurkovBA** [comment]
@ShipraShalini 

Sorry, what do you mean by "object like behaviour"?

**Comment by ShipraShalini** [comment]
@BurkovBA I am getting 
> Invalid embedded document instance provided to an EmbeddedDocumentField

after changing the code to use Dict keys instead of attribute.

**Comment by BurkovBA** [comment]
@ShipraShalini 

Hm, I use MapFields in my current project and they work fine. Can you supply the code, where you observed the error?

**Comment by ShipraShalini** [comment]
Sure.

This is the function that I use to update mapfields.

```
def update_mapfield(instance, validated_data, field):
    """
    updates mongoengine MapField by iterarting over keys
    :param instance: instance to be modified (document)
    :param validated_data: dict with new data
    :param field: field to be updated
    :return: None
    """
    for key, value in validated_data.items():
        for k, v in value.items():
            if k in value:   # for making sure that the already set field doesn't get overwritten with null
                try:
                    if isinstance(instance[field][key][k], list):
                        # update_set updates the list field instead of overwriting it
                        instance[field][key][k] = update_set(instance[field][key][k], validated_data[key][k])
                    else:
                        instance[field][key][k] = validated_data[key][k]
                except KeyError:
                    instance[field].update({key: value})
    instance.save()
```

**Comment by BurkovBA** [comment]
@ShipraShalini 

Wow, that's a lot of code. This should be simpler. :) 

So, you have a MapField of EmbeddedDocuments like this:

```
class Song(EmbeddedDocument):
    title = fields.StringField()
    context = fields.FileField()

class Album(EmbeddedDocument):
    date = fields.DateTimeField()
    songs = fields.EmbeddedDocumentListField(Song)

class RockBand(Document):
    albums = fields.MapField(fields.EmbeddedDocumentField(Album))
```


 and your `validated_data` looks like this:

```
{
    "Queen": {
        "Night in the Opera": {
            "date": "11-21-1975"
            "songs": [
                {
                    "title": "Bohemian Rhapsody",
                    "content": <urlencoded content>
                }
            ] 
        }
    }
}
```

Is your `field` a `DocumentSerializer` field or a `Document` field? It should be `Document` field, right?

Now, in my example `key=Night in the Opera`, `k="date", "songs" etc.`, so `validated_data[key][k]` is `"11-21-1975"` or `[{"title": "Bohemian Rhapsody", "content": <urlencoded content>}]`. The latter is not a valid `EmbeddedDocumentListField` - it's just a python list that needs to be converted to EmbeddedDocumentListField.

Same is true for any EmbeddedDocument you have - `validated_data[key][k]` is a dict, not EmbeddedDocument.

Also, I don't know, what is `update_set()` function, you're using.

**Comment by BurkovBA** [comment]
@ShipraShalini 

I believe, the whole idea of letting `validated_data` contain Mongoengine objects was a design error of DRF-Mongoengine 3.3.0.

I also think that you're manually doing what DRF-ME does for you automatically. I'm not sure about PATCH request and partial updates (there's an experimental patching.py module in contrib, responsible for that), but PUT request handles full updates of your MapFields well.

**Comment by ShipraShalini** [comment]
@BurkovBA 

update_set simply updates the ListField so that its elements are unique.
```
def update_set(array, element):
    """
    adds element to array if not already present
    :param array: array in which element has to be added
    :param element: element to be added
    :return: updated array
    """
    # gives error if I try to put the next three statements in one.
    arr = set(array)
    arr.update(element)
    return list(arr)
```

Modifying the mentioned example to be closer to my implementaion

```
class Album(EmbeddedDocument):
    date = fields.DateTimeField()
    songs = fields.ListField(StringField())

class RockBand(Document):
    albums = fields.MapField(fields.EmbeddedDocumentField(Album))
```

Here ```validated_data[field][key][k]``` is a date or list.
I wrote this code as DRF-ME 3.3.0 was overwriting the ListField and the Mapfield.
This is a simpler version of the code but i have to update a few fields, let's say based on conditions.

Is there anyway, i can fix this?

**Comment by BurkovBA** [comment]
@ShipraShalini
No, you couldn't have assigned a dict to the instance before - I believe, you were assigning EmbeddedDocument to EmbeddedDocument field. :)

Ok, may be you can just modify my code from [recursive_save()](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L211) and [update()](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L266) functions to have your task solved?

**Comment by ShipraShalini** [comment]
@BurkovBA 

I updated the ```update_mapfield``` function to fix it.

```
def update_mapfield(instance, validated_data, field, embedded_doc):
    """
    updates mongoengine MapField by iterarting over keys
    :param instance: instance to be modified (document)
    :param validated_data: dict with new data
    :param field: field to be updated
    :param embedded_doc: embedded document class
    :return: None
    """
    for key, value in validated_data[field].items():
        for k, v in value.items():
            if k in value:   # for making sure that the already set field doesn't get overwritten with null
                try:
                    if isinstance(instance[field][key][k], list):
                        # update_set updates the list field instead of overwriting it
                        instance[field][key][k] = update_set(instance[field][key][k], validated_data[field][key][k])
                    else:
                        instance[field][key][k] = validated_data[field][key][k]
                   instance[field][key][k] = embedded_doc(validated_data[field][key][k])
                except KeyError:
                    instance[field].update({key: embedded_doc(**value)})
    instance.save()
```

Thanks a lot for your help. Closing the issue.
