### ISSUE TITLE
Update issue when extra fields are passed.

### ISSUE THREAD

**Issue by cmaring** [umutbozkurt/django-rest-framework-mongoengine#211]
Not sure if this an issue but is it a required behaviour but are we really suppose to save data not defined in the serializer/model?

https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L252

I'm using django-mongoengine and I get errors on update whenever I pass extra fields which are not defined on serializer/model.

There may be chances that UI or thirdparty api consumers may accidentally pass such fields.

**Comment by BurkovBA** [comment]
@cmaring 

Yeah, I did this on purpose - if you want to allow those dynamic fields - use DynamicDocumentSerializer. 

Besides, great job that you managed to dig this deep!

**Comment by cmaring** [comment]
@BurkovBA 
That is a DocumentSerializer. The dynamic behaviour should only be allowed for DymanicDocumentSerializer. What do you say?

**Comment by BurkovBA** [comment]
@cmaring 
Ah, wait a minute, it seems like we're trying to save those arbitrary dynamic fields for `DocumentSerializer`, which is not intended. They should be either reported as error or at least discarded. They should be saved only in `DynamicDocumentSerializer`.

Ok, I'll write a unit-test for this, if it doesn't exist yet and fix this. Thanks a lot for reporting!

**Comment by BurkovBA** [comment]
@cmaring  Thank you for pointing this out, Constantine. 

I created [some tests](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_dynamic.py#L17) for this and currently unexpected dynamic data don't make it to MongoDB (not even to mongoengine object). They are filtered-out by [to_internal_value()](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L255) function, which accepts only those data, expected by the fields.

Now, should we raise an error, if user attempts to pass unexpected data to REST api? [DRF does not report this as an error by default](http://stackoverflow.com/questions/22178266/django-rest-framework-raise-error-when-extra-fields-are-present-on-post), so, I figured, I won't be reporting this either. If you want to raise a warning about this, you can customize `validate()` method as suggested in StackOverflow question.

> I'm using django-mongoengine and I get errors on update whenever I pass extra fields which are not defined on serializer/model.

Could you provide an example or a description of case, where you got errors? I'll fix them and add them to test suite, if I manage to reproduce them.

**Comment by BurkovBA** [comment]
I assume, this works ok.
