### ISSUE TITLE
how to use User Authentication 

### ISSUE THREAD

**Issue by MohamedShawky** [umutbozkurt/django-rest-framework-mongoengine#213]

**Comment by BurkovBA** [comment]
@MohamedShawky 

Hi, Mohamed. I'm working on this in [django-rest-framework-mongoengine-example](https://github.com/BurkovBA/django-rest-framework-mongoengine-examplel) project.

I've just started, but you can already take a look into [users app](https://github.com/BurkovBA/django-rest-framework-mongoengine-example/tree/master/project/users) there. Already, you can understand some things about how to integrate Mongoengine authentication system with django from that example.

That example replicates DRF's [authtoken](https://github.com/encode/django-rest-framework/tree/master/rest_framework/authtoken) app, which implements JSON [TokenAuthentication](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L143) scheme - when your client identifies user by a token, typically stored in your JS app or in LocalStorage/SessionStorage and sends it to server in `Authentication` header upon each request to itself. This Token is generated by server side of your application and returned to the client in exchange for a correct username/password combination by ObtainAuthToken view.

**Comment by BurkovBA** [comment]
@MohamedShawky

Mohamed, I created fully-functional TokenAuthentication example and a suite of tests with it. You can find it in [users app](https://github.com/BurkovBA/django-rest-framework-mongoengine-example/tree/master/project/users). I'm gonna write a paper specifically on authentication to explain, how it works, but for now you can copy-paste that example and read in-code documentation that explains, what's going on there.

**Comment by MohamedShawky** [comment]
@BurkovBA 
BurkovBA, Thanks for your interest و
when i download this  users app it didnot work 
i have download requirments 
if you can contact with me

**Comment by dblado** [comment]
Old thread, but how come the different authentication methods in DRF (Token, Basic, etc) aren't built in to django-rest-framework-mongoengine?

Has anyone been able to do OAuth2 w/ DRF+Mongoengine?

**Comment by dblado** [comment]
@BurkovBA, Yes mongoengine split django support off in to a sub package a while ago. Authentication has worked well with https://github.com/MongoEngine/django-mongoengine. How come django-rest-framework-mongoengine can't simply include the Token model from https://github.com/BurkovBA/django-rest-framework-mongoengine-example/blob/master/project/users/models.py#L199 and TokenAuthentication from https://github.com/BurkovBA/django-rest-framework-mongoengine-example/blob/master/project/users/authentication.py#L9

Wouldn't that let someone use DRF+mongoengine w/ token based authentication without having to include those pieces in their own code?

**Comment by BurkovBA** [comment]
@dblado David, if you have time to take those pieces of code, cover them with unit-tests and include submit a PR into django-rest-framework-mongoengine, I'll gladly accept it. I'm sorry, I'm totally out of time, I've switched to different languages and projects.
