### ISSUE TITLE
extra_kwargs for nested fields

### ISSUE THREAD

**Issue by BurkovBA** [umutbozkurt/django-rest-framework-mongoengine#215]
I suggest the following `extra_kwargs` syntax for constructing fields in `EmbeddedDocumentSerializer`:

```
clas PapaSerializer(DocumentSerializer):
    class Meta:
        model = Papa
        extra_kwargs={
            'kid.foo': {allow_blank: True}
        }
```

 - [X] EmbeddedDocuments
 - [ ] NestedEmbedded, BottomEmbedded 
 - [X] NestedReferences
 - [x] Compound fields
 - [x] EmbeddedDocumentListField
 - [x] test validate_methods()
 - [ ] validators
 - [ ] source fields - model field name might not be the same as serializer field name
 - [ ] uniqueness extra_kwargs

**Comment by Vayel** [comment]
@BurkovBA It does not seem to work:

```python
from rest_framework_mongoengine import serializers as mongoserializers
from mongoengine import Document, EmbeddedDocument, fields

class ChildDocument(EmbeddedDocument):
    name = fields.StringField(blank=True,)
    age = fields.IntField()

class CompoundParentDocument(Document):
    foo = fields.StringField()
    embedded_list = fields.EmbeddedDocumentListField(ChildDocument)
    list_of_embedded_documents = fields.ListField(fields.EmbeddedDocumentField(ChildDocument))
    embedded_map = fields.MapField(fields.EmbeddedDocumentField(ChildDocument))

class CompoundParentSerializer(mongoserializers.DocumentSerializer):
    class Meta:
        model = CompoundParentDocument
        fields = ('__all__')
        depth = 1
        extra_kwargs = {
            'foo': {'default': 'bar'},
            'embedded_list.child.name': {'default': 'Johnny'},
            'list_of_embedded_documents.child.name': {'default': 'B'},
            'embedded_map.child.name': {'default': 'Good'}
        }

from rest_framework.compat import unicode_repr
print(repr(CompoundParentSerializer()))
```

Output:

```
CompoundParentSerializer():
    id = ObjectIdField(read_only=True)
    foo = CharField(default='bar')
    embedded_list = EmbeddedSerializer(many=True, required=False):
        name = CharField(required=False)
        age = IntegerField(required=False)
    list_of_embedded_documents = EmbeddedSerializer(many=True, required=False):
        name = CharField(required=False)
        age = IntegerField(required=False)
    embedded_map = EmbeddedSerializer(many=True, required=False):
        name = CharField(required=False)  # No default
        age = IntegerField(required=False)
```

What I don't understand is that all tests in `test_nested_customization.py` pass.

My dependencies:

```
mongoengine==0.13.0
Django==1.11.2
django-rest-framework-mongoengine==3.3.1
djangorestframework==3.6.3
``` 

Thanks

**Comment by BurkovBA** [comment]
@Vayel 
Thank you for reporting this, Vincent! 

I'll have to add new versions of DRF, Mongonengine and Django to the test dependency matrix and check failures.

It's actually very strange that tests don't fail for you, cause I expected [this one](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_nested_customization.py#L225) to fail at the very least.

I'll work on this in the evening - currently busy with my day job. :)

**Comment by Vayel** [comment]
@BurkovBA 

I confirm the fact that the test passed. I ran it manually and printed `CompoundParentSerializer()`. The output is the one expected. It's very strange because if I copy the test code in `app/serializers.py`, an `AssertionError` is raised.

**Comment by BurkovBA** [comment]
@Vayel 

I have a suspicion that this bug might be similar to that with overridden DictField. =) 

Thing is DRF-ME redefines lots of representation functions in [repr module](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/repr.py). So, maybe, there are some issue with using `unicode_repr` from `rest_framework.compat`. Not sure, though.
