### ISSUE TITLE
DictField: help_text not taken into account

### ISSUE THREAD

**Issue by Vayel** [umutbozkurt/django-rest-framework-mongoengine#225]
Probably the same problem than #224. I have this model:

```python
class Model(Document):
    field = fields.MapField(fields.EmbeddedDocumentField('OtherModel'), help_text='help')
```

On the API, the help text does **not** appear whereas it does with a `StringField` for instance.

The help text **does** appear when I add it into `extra_kwargs`:

```python
class Serializer(DocumentSerializer):
    class Meta:
        model = Model
        fields = '__all__'
        extra_kwargs = {'field': {'help_text': 'help'}}
```

Thanks!

**Comment by Vayel** [comment]
@BurkovBA can I help here?

**Comment by BurkovBA** [comment]
I'm actually surprised that this is happening - it shouldn't. Here is parsing of `help_text` argument: https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/utils.py#L125.

If you could create a unit-test, confirming this issue, it would be very nice, thank you!

For instance, you could modify either test_basic or test_compound, adding `help_text` argument to one of the fields:

- https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_basic.py#L185
- https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_compound.py

**Comment by Vayel** [comment]
Indeed, it works. I am sorry, I redefined the field in my serializer so the attributes of the model were not used. To remedy that, I used `extra_kwargs` instead of redefinition:

```python
class Collection(Document):
    posts = fields.MapField(
        fields.EmbeddedDocumentField('Post'),
        blank=True,
        help_text='Help!',
    )

class CollectionSerializer(mongoserializers.DocumentSerializer):
    class Meta:
        model = models.Collection
        fields = '__all__'
        extra_kwargs = {
            'posts': {
                'child': PostSerializer(),
                'validators': [validate_posts_dict],
            }
        }
```
