### ISSUE TITLE
StringField possibly blank but not null?

### ISSUE THREAD

**Issue by Vayel** [umutbozkurt/django-rest-framework-mongoengine#227]
Hi!

How can I have a `StringField` with `allow_blank=True` and `allow_null=False`. DRF-ME puts both args to `True` when `StringField().null == True`. 

Do I have to add it manually to my serializer, like below?

```python
class Document(me.Document):
    title = fields.StringField(required=True,)

class DocumentSerializer(mongoserializers.DocumentSerializer):
    class Meta:
        model = models.Document
        fields = '__all__'
        extra_kwargs = {
            'title': {'allow_blank': True},
        }
```

Thanks

**Comment by BurkovBA** [comment]
@Vayel 
Hi!

Yes, for StringField 'null' in Mongoengine means 'null' and 'blank' in serializer:
https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/utils.py#L153

Yep, you can override that in `extra_kwargs`.

**Comment by Vayel** [comment]
Thanks for the confirmation!
