### ISSUE TITLE
Error with non-ObjectId primary key in referenced field

### ISSUE THREAD

**Issue by Vayel** [umutbozkurt/django-rest-framework-mongoengine#228]
Hi!

I have the following models:

```python
class Parent(Document):
    child = ReferenceField('Child')


class Child(Document):
    text = StringField(primary_key=True)
```

An `OPTIONS` request on the `Parent` endpoint in the browsable API displays something like:

```
// ...
"child": {
    "type": "field",
    "required": true,
    "read_only": false,
    "label": "Type",
    "choices": [
        {
            "value": "word",
            "display_name": "USLType object"
        }
    ]
}
// ...
```

But when I send this `POST` request:

```
{
    "child": "word"
}
```

I obtain the error:

```
{
    "child": [
        "Cannot parse \"text1\" as ObjectIdField."
    ]
}
```

If I send the request with the id of the `Child`:

```
{
    "child": "5947f817561e3ad0aacfc6be"
}
```

I obtain the Django error:

```
LookUpError at /library/usls/

Cannot resolve field "id"
```

Thanks

**Edit :** explanations [here](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/2067a702837a2387c7c1c01b2d296b44a53d25b5/rest_framework_mongoengine/fields.py#L211).

**Comment by BurkovBA** [comment]
@Vayel 

Hi! Yes, there's an issue with `id`. Try manually creating a primary key for `text` on `ChildSerializer`.

**Comment by Vayel** [comment]
@BurkovBA can I help here?
