### ISSUE TITLE
How do I use auth token?

### ISSUE THREAD

**Issue by erdenezul** [umutbozkurt/django-rest-framework-mongoengine#247]

**Comment by BurkovBA** [comment]
Hi, @erdenezul 

You pass it from frontend to your backend in Authorization token on each request to associate this request with particular user as described in [TokenAuthentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) documentation.

**Comment by erdenezul** [comment]
@BurkovBA I am using django_mongoengine and have no idea to support it.

**Comment by BurkovBA** [comment]
@erdenezul You can just follow this example: https://github.com/BurkovBA/django-rest-framework-mongoengine-example.

It has a [users app](https://github.com/BurkovBA/django-rest-framework-mongoengine-example/tree/master/project/users) that implements TokenAuthentication.

**Comment by erdenezul** [comment]
@BurkovBA thanks for your help
