### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Niyojan** [umutbozkurt/django-rest-framework-mongoengine#259]
Last commit was 16 Dec 2017.
Do we have any active alternatives?

**Comment by loicgasser** [comment]
Yes maybe specify it on the README of the project.
It seemed like a cool project, I guess I'll try djongo or forget about django and mangodb and use something like flask.

**Comment by BurkovBA** [comment]
@loicgasser 
I'll probably write something like "Maintainer needed". 

It's been just a few years, and the world has changed entirely already, what seemed promising to me, now feels like a waste of time...

**Comment by smn-snkl** [comment]
@BurkovBA : Why do you say it feels like a waste of time? What were the issues you were facing?

**Comment by loicgasser** [comment]
I guess keeping up with django + django rest framework + mangodb

**Comment by BurkovBA** [comment]
@smn-snkl I'm trying to spend all my spare time on machine learning now. This project is just another piece of glue code between another 2 technologies, while we're not so far from decent level of automation of programming in general, I believe. So, I can't help but spending all my spare time there, sorry, mate. Terribly exciting area.

**Comment by cmdedj** [comment]
@BurkovBA 
I hope you can succeed on machine learning in the future～！
and then hope you can back to the project, much of us need it.

**Comment by uoxiu** [comment]
This project is still maintained to work with last versions of Django and DRF but we don't cover all features from last DRF releases, we need maintainers :(
