### ISSUE TITLE
Will it support django2.x in the future?

### ISSUE THREAD

**Issue by cmdedj** [umutbozkurt/django-rest-framework-mongoengine#267]
Will it support django2.x in the future?

**Comment by BurkovBA** [comment]
I'm sorry, I'm very much out of time to work on this project lately. It's pretty low on my priorities list now, so I can't promise I will update it in the next few months. Take care.

**Comment by cmdedj** [comment]
> I'm sorry, I'm very much out of time to work on this project lately. It's pretty low on my priorities list now, so I can't promise I will update it in the next few months. Take care.

i know, thank you~

**Comment by uoxiu** [comment]
@cmdedj hi, i use this package in django 2.x. ViewSets, DocumentSerializer and GenericApiView works well

**Comment by cmdedj** [comment]
@uoxiu thank you very much~ >.<

**Comment by uoxiu** [comment]
Successfully tested on Django 2.2, last DRF and me 0.18
https://travis-ci.org/umutbozkurt/django-rest-framework-mongoengine

**Comment by cmdedj** [comment]
@uoxiu nice，thank you on behalf of everyone.
