### ISSUE TITLE
Support for drf 3.10.x release.

### ISSUE THREAD

**Issue by Betalos** [umutbozkurt/django-rest-framework-mongoengine#269]
Well I know by reading the other issue that this a low priority project. But is it possible to just adjust the code as it is just to work with the new version of drf.

**Comment by benxy** [comment]
I noticed problem with non-existing `unicode_repr` function from rest_framework.compat.
Did you find anything else?

**Comment by Betalos** [comment]
@benxy, Well I didn't noticed something else. But I didn't investigate further.

**Comment by talhaishtiaq** [comment]
Getting error:
    from rest_framework.compat import unicode_to_repr
ImportError: cannot import name 'unicode_to_repr' from 'rest_framework.compat' (/Users/talha/Projects/djangoproject/env/lib/python3.7/site-packages/rest_framework/compat.py)

**Comment by Betalos** [comment]
@talhaishtiaq, well for now you'll have to downgrade drf to 3.9.4. Until a fix is published.

**Comment by benxy** [comment]
According to [commit](https://github.com/encode/django-rest-framework/commit/0407a0df8a16fdac94bbd08d49143a74a88001cd#diff-ce493f71b3679e91b72126c168670399) in django-rest-framework, this was dropped as a part of removing python2 compatibility.
@BurkovBA would then a solution be also to drop compatibility for python2? I just removed the functions in my forked version.

**Comment by talhaishtiaq** [comment]
@benxy So is it working in your forked version?
who uses Python 2 these days

**Comment by talhaishtiaq** [comment]
its a very nice plugin for MongoDB and Django integration
How can I start contributing?
@Betalos I have changed the version of drf to 3.9.4 and its working good.
sql is very slow than nosql MongoDB
queries in Django api are much faster after migrating with mongoengine.
Can we add 'makermigration' and 'migrate' support?
As you have to do custom migration using Model.save().
it'll be awesome if 'makermigration' and 'migrate' are added.

**Comment by BurkovBA** [comment]
@benxy Hi, folks! I see your issue, but I'm currently very busy on the weekdays, sorry. Will take a look on the weekend.

DRF 3.9 has dropped support for python2, so I'll modify testing matrix in .tox to support only python3 for DRF 3.9.

**Comment by Betalos** [comment]
@BurkovBA *DRF 3.10.* (3.9 is still working).

**Comment by benxy** [comment]
Np @BurkovBA. Thanks!

**Comment by talhaishtiaq** [comment]
I just removed the unicode_repr from
repr.py
serializers.py
validators.py

and its working with DRF 3.10.x

**Comment by uoxiu** [comment]
@BurkovBA Hi, you do not want to give maintainer access to someone? because a simple change takes a lot of time and pull requests are ignored

**Comment by uoxiu** [comment]
Fixed and available in v3.4.0

**Comment by joyhuchao** [comment]
could you add the function in the last version?
