### ISSUE TITLE
Doesn't work with djangorestframework=^3.10.2 

### ISSUE THREAD

**Issue by Zuiluj** [umutbozkurt/django-rest-framework-mongoengine#271]
https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/2fe6de53907b31a5e8b742e4c6b728942b5fa4f0/rest_framework_mongoengine/serializers.py#L10

'unicode_to_repr' function already removed, causes ImportError trying to import something that does not exist in rest_framework's 'rest_framework.compat'

Kind regards,

**Comment by uoxiu** [comment]
Fixed and available in v3.4.0
