### ISSUE TITLE
Compatible with Django 3.0

### ISSUE THREAD

**Issue by LKI** [umutbozkurt/django-rest-framework-mongoengine#273]
Django 3.0 remove vendored library `django.utils.six`, ref: [django 3.0 changelog](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis)

But we use it in [rest_framework_mongoengine/serializers.py](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py)

So there will be an error:
```
ModuleNotFoundError: No module named 'django.utils.six'
```

**Comment by uoxiu** [comment]
@LKI Thanks for reporting, in the next few days we will fix this

**Comment by uoxiu** [comment]
@LKI fixed in the new release, 3.4.1 

https://pypi.org/project/django-rest-framework-mongoengine/3.4.1/

**Comment by LKI** [comment]
Thanks!
