### ISSUE TITLE
Is it possible to enable cache?

### ISSUE THREAD

**Issue by wdxwj** [umutbozkurt/django-rest-framework-mongoengine#291]
Since there are too much data in the mongodb, it costs lots of time when querying. Is it possible to enable cache?

**Comment by IATF** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BurkovBA** [comment]
Do you mean something like `caching.base.CachingMixin` and `caching.base.ContextManager` and something like memached? 

I've never tried doing so with MongoDB.

**Comment by wdxwj** [comment]
> 

Yes. But, I solved my problem using Index. So, I don't need cache any more.
