### ISSUE TITLE
ImageField return null

### ISSUE THREAD

**Issue by lewang0418** [umutbozkurt/django-rest-framework-mongoengine#50]
When uploading an image in ImageField, django-rest-framework returns warning "Upload a valid image. The file you uploaded was either not an image or a corrupted image." and the returned value is null. However, image.files and image.chunks can be found in mongodb. The problem is how to get URL of uploaded image correctly?

**Comment by umutbozkurt** [comment]
will check this after updating to DRF 3, sorry for late response

**Comment by jcodebrain** [comment]
Excuse me, Did you fix this ImageField issue?
