### ISSUE TITLE
doesn't support DRF 3.0+

### ISSUE THREAD

**Issue by alexlucky** [umutbozkurt/django-rest-framework-mongoengine#53]
Since DRF 3.0+ doesn't have Writable Field and ModelSerializerOptions any more, this repo doesn't support mongodb models currently. Any plan to upgrade it to a version which bases on DRF 3? Thank you.

**Comment by umutbozkurt** [comment]
Yes, I will develop DRF 3 support this weekend hopefully

**Comment by umutbozkurt** [comment]
Support for DRF 3 is done. I will rewrite whole documentation and readme later this week

**Comment by alexlucky** [comment]
Thank you for the effort! It's working well so far in my project!!!

**Comment by tweiand-10m2** [comment]
Thank you!
