### ISSUE TITLE
please, release DRF-3.0 compatible version 

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#54]
You have closed related issue, but no released version exists.
(1.4.3 at github releases and 1.5.4 at pipy are incompatible)

**Comment by umutbozkurt** [comment]
please check readme, thanks

**Comment by umutbozkurt** [comment]
I will be releasing a new version this evening

**Comment by umutbozkurt** [comment]
https://github.com/umutbozkurt/django-rest-framework-mongoengine/releases/tag/v2.0
