### ISSUE TITLE
ListField is unnecessary

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#56]
ListField is now implemented in drf-3.0
And anyway it should not be DocumentField, because can be used outside of DicumentSerializer context.

**Comment by umutbozkurt** [comment]
DRF ListField is not automatically inject the field to serializer like we do. You should manually define a ListField in order to have it. So it is necessary for this package to have a ListField which automates the work on Mongoengine's ListField

**Comment by qwiglydee** [comment]
This is a point that i miss.
What is special about the injection, except depth handling?

The issue is that this ListField cannot be used in non-modelserializer, because of model_field requirement.

**Comment by umutbozkurt** [comment]
Well, for non-modelserializers you can always use DRF ListField
