### ISSUE TITLE
DictField is still necessary

### ISSUE THREAD

**Issue by qwiglydee** [umutbozkurt/django-rest-framework-mongoengine#57]
For both serializers and documentserializers.

Add-on implementations, like drf-compund-fields cannot be used without patching DocumentSerializing.field_mapping.

I have implemented it in the similar way as rest_framework.fields.ListField and can provide patch/pullrequest.

A question still remains whether children/subfields definition should be strict and unexpected items should be reported, or undeclared items should go as strings without errors.
My guess is that for strict subfields embedded documents should be used.

**Comment by umutbozkurt** [comment]
Yes, on latest release, you can use nested serializers for Mongoengine's ListField.
DictField will also be supported on latest release

**Comment by qwiglydee** [comment]
dict fields are used for data that cannot be described as nested documents.
i.e. keys are not known a priory.
nested serializers cannot be used in such cases

**Comment by umutbozkurt** [comment]
Exactly, thats why you cant use nested serializers on dict field.
