### ISSUE TITLE
You should either call `.is_valid()` first, or access `.initial_data` instead.

### ISSUE THREAD

**Issue by akhilclarion** [umutbozkurt/django-rest-framework-mongoengine#62]
Hi umutbozkurt,

I am new to the django rest framework with mongoengine. Please help me with below error.

When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.

**Comment by umutbozkurt** [comment]
It basically says that you should call `.is_valid()` before accessing `.data` property

**Comment by umutbozkurt** [comment]
The issue is on new DRF version, will let you know when its fixed

**Comment by umutbozkurt** [comment]
DRF version 3.0.2 and above will be effected from this

**Comment by dsljjmark** [comment]
I downgrade DRF to be 3.0.2 but it's not working

**Comment by umutbozkurt** [comment]
You should downgrade to 3.0.1

**Comment by umutbozkurt** [comment]
I found the bug, it is DRF related. I will report this issue and let you know

**Comment by dsljjmark** [comment]
Thank you , DRF version 3.0.1 is working

**Comment by umutbozkurt** [comment]
You can track DRF issue on https://github.com/tomchristie/django-rest-framework/issues/2440

**Comment by umutbozkurt** [comment]
Turns out this is DRFME bug, will try to fix this later tomorrow

**Comment by akhilclarion** [comment]
Hi umut,


Thanks you much for your valuable "Time".

**Comment by navneet35371** [comment]
facing similar issues
![selection_001](https://cloud.githubusercontent.com/assets/4524905/5873136/5d69a5c8-a319-11e4-9be6-3dfc65a9c36a.png)

**Comment by tweiand-10m2** [comment]
Looking at your constructor for DocumentSerializer

**Comment by tweiand-10m2** [comment]
django-rest-framework-mongoengine/rest_framework_mongoengine/serializers.py

112:    def __init__(self, instance=None, data=None, **kwargs):
113:        super(DocumentSerializer, self).__init__(instance=instance, data=data, **kwargs)

Should be (and fixes this issue):

112:    def __init__(self, instance=None, data=empty, **kwargs):
113:        super(DocumentSerializer, self).__init__(instance=instance, data=data, **kwargs)

I have a sub-class the just changes the kwargs for __init__ and this is resolved these issue for me.

**Comment by tweiand-10m2** [comment]
Looking at your constructor for DocumentSerializer:
django-rest-framework-mongoengine/rest_framework_mongoengine/serializers.py

Line 112-113:
```python
def init(self, instance=None, data=None, *kwargs):
    super(DocumentSerializer, self).init(instance=instance, data=data, *kwargs)
```
Should be something like this (the data kwarg is the change):

```python

from rest_framework.fields import empty

def init(self, instance=None, data=empty, *kwargs):
     super(DocumentSerializer, self).init(instance=instance, data=data, *kwargs)
```

I have a sub-class the just changes the kwargs for init and this is resolved these issue for me.

**Comment by umutbozkurt** [comment]
Yes! This fixes it. Thanks for help I was struggling to fix this. `data=empty` kwarg must have fall through the cracks.

**Comment by tweiand-10m2** [comment]
Glad I can help! And, totally agreed, weird one to track down.

**Comment by lilida** [comment]
Got the same issue. When will you bump the version so I can pick the fix?

Thanks

**Comment by umutbozkurt** [comment]
You can pick the fix on version `2.0.2`

**Comment by lilida** [comment]
Great! Thanks a lot

**Comment by yuyou** [comment]
Hi

I am not sure if this is the valid thread. But the latest "DocumentSerializer" in the source tries to invoke the super member function "is_valid()". The syntax raises exceptions in Python 2.7.

valid = super().is_valid(raise_exception=raise_exception)

Are you sure it is the correct way to invoke super method in Python 2.7? At least I got exceptions said "super() takes at least 1 argument (0 given)"

And my IDE says Python 2.7 does not support that syntax.

Thanks.

Yu

**Comment by qwiglydee** [comment]
right thread is here: 
https://github.com/umutbozkurt/django-rest-framework-mongoengine/issues/142

**Comment by rajansahu713** [comment]
the same issue got in django=3.2.1

**Comment by lgl8023** [comment]
I also got this error when I serialized custom validate() validation in Django2.2.9
