### ISSUE TITLE
Query results are not always up-to-date (get_queryset not refreshing)

### ISSUE THREAD

**Issue by tweiand-10m2** [umutbozkurt/django-rest-framework-mongoengine#63]
### Short story:
Sometimes I can get 'stale' results when querying a database. Database had correct values. REST interface showed previous value.

### Long story:
One of my unit tests was reporting the wrong value from an endpoint I was doing list operations on. I would do a POST (successfully completed) with a GET immediately after it.

### My work-around:
I noticed that get_queryset was not defined in GenericAPIView. In rest_framework/generics.py the GenericAPIView checks that the query set is of type QuerySet (which is not the case).

### Root cause analysis lead me here:
django-rest-framework-mongoengine/rest_framework_mongoengine/generics.py

Better fix than this (major hack):
```python
class GenericAPIView(drf_generics.GenericAPIView):

    def get_queryset(self):

        queryset = self.queryset
        self.logger.debug('refreshing query set')
        queryset = queryset.all()

        return queryset
```

**Comment by umutbozkurt** [comment]
Thanks for heads up, fixed on 3b75cc0e0d6a05d0f1699e4f2dc882588aa3eec9
