### ISSUE TITLE
Serializers error: 'FileField' object has no attribute 'max_length'

### ISSUE THREAD

**Issue by kiatweitan** [umutbozkurt/django-rest-framework-mongoengine#65]
Looks like mongoengine's FileField doesn't have this attribute. So are EmailField and URLField. This is needed for DRF's FileInput widget though. (ref line 340-342 in serializers.py)

**Comment by umutbozkurt** [comment]
Thanks for heads up, will try to resolve it this weekend

**Comment by yamatt** [comment]
Still experiencing this on 2.0.2/3

**Comment by yamatt** [comment]
Looks like it just needs https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/rest_framework_mongoengine/serializers.py#L351 removed

**Comment by qwiglydee** [comment]
should not bean issue in last release.
