### ISSUE TITLE
Problem with EmbeddedDocumentSerializers

### ISSUE THREAD

**Issue by optik** [umutbozkurt/django-rest-framework-mongoengine#72]
**Problem description**
When there is an embedded serializer field defined in the root document serializer, DRF's BaseSerializer will throw a "Cannot call `.is_valid()` as no `data=` keyword argument waspassed when instantiating the serializer instance." AssertionError in is_valid method, **create** use case, based on the following assertion:
```python
        assert hasattr(self, 'initial_data'), (
            'Cannot call `.is_valid()` as no `data=` keyword argument was'
            'passed when instantiating the serializer instance.'
        )
```
The first that comes to mind is that the following code in DocumentSerializer is failing to set the required property:
```python
    def is_valid(self, raise_exception=False):
        valid = super(DocumentSerializer, self).is_valid(raise_exception=raise_exception)
        for embedded_field in self.embedded_document_serializer_fields:
            embedded_field._initial_data = self.validated_data.pop(embedded_field.field_name, serializers.empty)
            valid &= embedded_field.is_valid(raise_exception=raise_exception)
        return valid
```
Changing **_initial_data** to **initial_data** seems to fix the issue (looks like that only **initial_data** is used by BaseSerializer in DRF3), though I'm not sure of the consequences...

Test case:
```python
# models:

class EmbeddedTest(EmbeddedDocument):
    int_field = IntField()

class Test(Document):
    string_field = StringField()
    dynamic_field = EmbeddedDocumentField(EmbeddedTest)

# serializers:

class EmbeddedTestSerializer(EmbeddedDocumentSerializer):

    class Meta:
        model = EmbeddedTest
        depth = 1


class TestSerializer(DocumentSerializer):
    dynamic_field = EmbeddedTestSerializer(many=False)

    class Meta:
        model = Test
        depth = 1

```

**Comment by umutbozkurt** [comment]
Thanks for pointing that out. Which version of DRF are you using?

**Comment by optik** [comment]
I'm using DRF 3.0.4 (latest)

**Comment by optik** [comment]
Additionally, I think there may be a problem with this block of code in DocumentSerializer, in a scenario where EmbeddedDocumentSerializer is explicitely defined as a field:
```python
for embedded_field in self.embedded_document_serializer_fields:
    embedded_field._initial_data = self.validated_data.pop(embedded_field.field_name, serializers.empty)
    valid &= embedded_field.is_valid(raise_exception=raise_exception)
```
I'm not 100% sure, but I think what happens is that the serializer is registered both as a field and in *embedded_document_serializer_fields* property of the parent serializer (in the *get_fields* method), resulting in the validation being run twice. The first time it's called as a result of calling *is_valid* on a root DocumentSerializer (from *run_validation*), with raw data dict ("normal" DRF flow). The second time the validation is run by calling is_valid directly on the embedded serializer with the data that I think is already validated and passed as OrderedDict. The latter is a bit of an issue, imho.

**Comment by qwiglydee** [comment]
Please check the issue with current trunk.

**Comment by qwiglydee** [comment]
embedded validation should work now
