### ISSUE TITLE
GeoPointField support needed

### ISSUE THREAD

**Issue by arinconc** [umutbozkurt/django-rest-framework-mongoengine#79]
Updating to version 2.0.2, the framework fails with GeoPointField declaration:
u"<class 'mongoengine.fields.GeoPointField'> is not supported, yet. Please open a ticket regarding this issue and have it fixed asap.\nhttps://github.com/umutbozkurt/django-rest-framework-mongoengine/issues/"
With a previous version, we were able to use this field in a model or at least to use it in the declaration.
Thanks and keep the great work !!

**Comment by qwiglydee** [comment]
Keep in mind, that GeoPointField is somewhat depricated ("legacy way") in favor of PointField which is able to make 2dsphere indexes.

**Comment by crhuber** [comment]
@qwiglydee PointField doesnt seem to be supported yet either
<class 'mongoengine.fields.PointField'> is not supported, yet. Please open a ticket regarding this issue and have it fixed

**Comment by arinconc** [comment]
Ok
Thanks a lot!
;)
