### ISSUE TITLE
class 'mongoengine.fields.SequenceField is not supported, yet

### ISSUE THREAD

**Issue by arinconc** [umutbozkurt/django-rest-framework-mongoengine#83]
Is there an alternative to SequeceField?

Best regards,
Antonio

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by tweiand-10m2** [comment]
+1 on this ticket also

**Comment by qwiglydee** [comment]
Supported in trunk, but only as an integer. 
See [RegularFieldMappings](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_1basic.py#L124).
