### ISSUE TITLE
Serializer' object has no attribute '_include_additional_options'

### ISSUE THREAD

**Issue by shivamsingh** [umutbozkurt/django-rest-framework-mongoengine#84]
'<Model>Serializer' object has no attribute '_include_additional_options'

env\lib\site-packages\rest_framework_mongoengine\serializers.py in get_fields
            raise TypeError(
                'The `exclude` option must be a list or tuple. Got %s.' %
                type(exclude).__name__
            )
        assert not (fields and exclude), "Cannot set both 'fields' and 'exclude'."
        extra_kwargs = self._include_additional_options(extra_kwargs) ...
        # # Retrieve metadata about fields & relationships on the model class.
        info = get_field_info(model)
        # Use the default set of field names if none is supplied explicitly.
        if fields is None:

**Comment by shivamsingh** [comment]
# Serializer 

class AppSerializer(DocumentSerializer):
	class Meta:
		model = App
		fields = ('name', 'version)

**Comment by AnilSener** [comment]
hi Umut,
Any news regarding this problem? I am very dependent on this package to finish a university package in a few days? Simply it is not possible to go on without specifying extra_kwargs in simple serialization cases. Even f I tried to give some arguments, it didn't resolve the issue. Another additional benefit might be including Geopoint and PointField to the serializable fields list.
Thank you,
Anıl

**Comment by gdromero** [comment]
I have the same problem. Is there any solution?

Thanks.

**Comment by optik** [comment]
I remember having the same issue after upgrading my project dependencies to the latest versions (the culprit was either Django Rest Framework or PyMongo). Downgrading PyMongo to 2.8 and DRF to 3.0.4 helped.

**Comment by gdromero** [comment]
It works! Thank you.

**Comment by tweiand-10m2** [comment]
I started seeing this error once I updated from DRF 3.0.5 -> DRF 3.1.0.

**Comment by asemoon** [comment]
Same problem here, any plans for fixing the current version?

**Comment by tweiand-10m2** [comment]
I have a possible fix in pull request https://github.com/umutbozkurt/django-rest-framework-mongoengine/pull/88. Just wanting for review then possibly integration.

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by shivamsingh** [comment]
thanks a ton.

**Comment by shivamsingh** [comment]
I am new to python otherwise would have helped.

**Comment by iorlas** [comment]
@umutbozkurt please, we really need it since we need 3.1 fields behavior and we use mongoengine. I don't really want to switch to another github repo for this.

**Comment by morenopc** [comment]
Same problem here. Downgrading PyMongo and DRF seems to stop it.  
```
requirements.txt
djangorestframework==3.0.5
django-rest-framework-mongoengine==2.0.2 (latest)
pymongo==2.8
mongoengine==0.9.0 (latest)
```

**Comment by samarthmed** [comment]
@ owner : Any updates for this ? 

Using drf version 3.1.1 and drf-mongoengine version 2.0.2 (default from pip) . The self object doesn't have an attribute '_include_additional_options'.

**Comment by javiermatos** [comment]
Well, I am having the same issue. My environment has DRF 3.1.1, DRF-mongoengine 2.0.2 and Django 1.8.0.

What I have detected is a "temporary relation for this issue". If I use a breakpoint in the serializer.is_valid(raise_exception=True) line, then I go to my IDE, press to continue and it works fine. If I remove the break point it fails with exactly the same error message. Is there any temporary dependency that makes this to happen? Well, I don't think is a temporary dependency because if I force the view to wait (with python time.sleep(2) introducing some delay in the same way as the break point it still fails).

My code looks like this:

    serializer = MySerializer(data=request.DATA, many=True)
    serializer.is_valid(raise_exception=True)  # I put the break point here and resume to make it work
    data = serializer.validated_data

Maybe that could help.

**Comment by rcorzogutierrez** [comment]
I resolved to DRF 3.1 follows (overwriting the class)
```
class CustomModelSerializer(ModelSerializer):

    def _include_additional_options(self, *args, **kwargs):
        return self.get_extra_kwargs()

    def _get_default_field_names(self, *args, **kwargs):
        return self.get_field_names(*args, **kwargs)


class CustomDocumentSerializer(CustomModelSerializer, DocumentSerializer):
    pass
```

**Comment by bsmartt13** [comment]
That fixes the issue for me, thanks.

**Comment by qwiglydee** [comment]
duplicates #110
