### ISSUE TITLE
how to serialize ObjectId with different field name?

### ISSUE THREAD

**Issue by himanshujain2010** [umutbozkurt/django-rest-framework-mongoengine#85]
My user serializer looks like this

class UserSerializer(DocumentSerializer):
     user_id = serializers.Field(source='id')
     class Meta:
          model = Question
          depth = 2
          fields = ('user_id','name','address')

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by qwiglydee** [comment]
Why it is an issue?

DocumentSerializer has mapping of `mongoengine.fields.ObjectIdField` to `drf_mongoengine.fields.ObjectIdField` (and also for ReferenceField)
It should be autogenerated well.

**Comment by himanshujain2010** [comment]
i cannot change field name at the time of serialization

**Comment by qwiglydee** [comment]
Your case should work now.
But declared fields are not subject of any mungling (like making it readonly and putting some validations, you need to handle it yourself).

Also, option primary_key is now [respected](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_1basic.py#L233). You may rename your pk in model definition.
