### ISSUE TITLE
LongField is not supported, yet.

### ISSUE THREAD

**Issue by weiztech** [umutbozkurt/django-rest-framework-mongoengine#90]
Hi , i try to use and the serializer with longfield and go this error:

repr(...) failed: KeyError: u"class 'mongoengine.fields.LongField' is not supported, yet.

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by zzzuzik** [comment]
:+1:

**Comment by iorlas** [comment]
Yeaah.. so.. wuzzup?

**Comment by sudhakso** [comment]
Do you have a fix for having LongField.

**Comment by qwiglydee** [comment]
fixed in trunk
