### ISSUE TITLE
Reference field not json serializable

### ISSUE THREAD

**Issue by weiztech** [umutbozkurt/django-rest-framework-mongoengine#91]
i get  error when try to include ReferenceField on serializer
```python
class Tester(Document):
    author = ReferenceField(User)
    title = StringField()
    message = StringField()
    is_public = BooleanField(default=True)
    created_at = DateTimeField(default=timezone.now)

from rest_framework_mongoengine.serializers import DocumentSerializer
class TestSerializer(DocumentSerializer):
    class Meta:
        model = tester
        fields = ('id', 'is_public', 'created_at', 'author')

ObjectId('54c6375b278434122c7a5699')) is not JSON serializable

anyone here know how to solve this issue? 
i used drf 3.0.5 with django-rest-framework-mongoengine==2.0.2

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by weiztech** [comment]
@umutbozkurt  Thanks :-) .

**Comment by weiztech** [comment]
is there any fix for this issue ??

**Comment by d0c-s4vage** [comment]
I ran into this problem as well.

In my case, one of my models (model A) contains a reference field to a different model (model B). Everything works fine until I delete the model B document that model A was referencing. That's when I get the `ObjectId... is not JSON serializable` error.

**Comment by qwiglydee** [comment]
ReferenceField completely reimplemented.
Sould work now.
