### ISSUE TITLE
mongoengine DecimalField will no work on the DocumentSerializers.

### ISSUE THREAD

**Issue by hackrole** [umutbozkurt/django-rest-framework-mongoengine#93]
```bash
/usr/local/lib/python2.7/dist-packages/rest_framework_mongoengine/serializers.py(304) in get_fields
            ret[field_name] = field_cls(**kwargs) 
```
this is the error msg, the error was because rest-framework DecimalField need two required Field: max_digits, decimal_places,. which cannot set or get from the mongoengine DecimalField.

**Comment by umutbozkurt** [comment]
This issue will be addressed on weekend, sorry for late response

**Comment by qwiglydee** [comment]
Fixed in trunk

See [test](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_1basic.py#L124)
