### ISSUE TITLE
'QuerySet' object has no attribute 'model' when using Document model and rest_framework_mongoengine.viewsets.ModelViewSet

### ISSUE THREAD

**Issue by ghanemar** [umutbozkurt/django-rest-framework-mongoengine#94]
Hello,

I am getting

'QuerySet' object has no attribute 'model'  when using Document model and rest_framework_mongoengine.viewsets.ModelViewSet
my view is 

class JobViewSet(viewsets.ModelViewSet):
    queryset = Job.objects.all()
    serializer_class = JobSerializer

my serializer is 

class JobSerializer(DocumentSerializer):
    class Meta:
        model = Job
        fields = ('title', 'state')

and my model is

class Job(Document):
    title = StringField(required=True)
    state = StringField(required=True)

**Comment by umutbozkurt** [comment]
You should use drfme's viewsets not drf's. But, using viewsets with DRF-ME could be problematic, I do not actively maintain `viewsets`.

You are welcome to open a PR about this

**Comment by ghanemar** [comment]
Thanks Umut,

excuse my ignorance but I am using rest_framework_mongoengine.viewsets.ModelViewSet
is that what you mean by saying I should use drfme's viewsets?

**Comment by umutbozkurt** [comment]
Yes, thats what you should use, but as I mentioned before, it's not
actively supported

2015-04-02 12:10 GMT+03:00 Amer Ghanem <notifications@github.com>:

**Comment by lucapinello** [comment]
Same problem here.

**Comment by kkuet** [comment]
Same problem :(, 
The exception is
Exception Location:	/usr/local/lib/python2.7/dist-packages/rest_framework/permissions.py in has_permission, line 125

**Comment by blackboxx** [comment]
So sad, i have same problem

**Comment by qwiglydee** [comment]
It seems like it's gone long ago.
Please, make a testcase for the issue.

**Comment by carlosfelipe29** [comment]
I am new working with this king of API, I have been using Django 1.8.5 and mongoDB mongoengine 0.10.0, but I can't get this work (to raise the connections)  localhost/api/... .   
Do you know a guide or documentation about it. I got several errors with 'module' object has no attribute 'PersonaViewSet', when I changed some imports  the same thing but  'views' is not defined.
I apprecited your help.

**Comment by qwiglydee** [comment]
@carlosfelipe29 please describe yourproblem exact:
What code do you run, what is expected result, what result do you get.

Also, you may download/clone sources and write a test using 
(this template)[https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_0dumb.py]

**Comment by 0xfib** [comment]
Same here! Will be great if someone will get the bottom of this.

**Comment by BurkovBA** [comment]
@0xfib

As Umut mentioned earlier, you should use modified viewsets from drf-me, not from drf:
 
```
from rest_framework_mongoengine.viewsets import ModelViewSet
```

Also, I'd suggest replacing

```
class JobViewSet(viewsets.ModelViewSet):
    queryset = Job.objects.all()
```

with 

```
class JobViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        return Job.objects.all()
```

to be safe against eager execution of request.

Does that help?

**Comment by 0xfib** [comment]
Still the same problem:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/tool/

Django Version: 1.9
Python Version: 3.6.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework_mongoengine',
 'drf']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware']



Traceback:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  466.             response = self.handle_exception(exc)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  454.             self.initial(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in initial
  377.         self.check_permissions(request)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in check_permissions
  318.             if not permission.has_permission(request, self):

File "/usr/local/lib/python3.6/site-packages/rest_framework/permissions.py" in has_permission
  125.         perms = self.get_required_permissions(request.method, queryset.model)

Exception Type: AttributeError at /tool/
Exception Value: 'QuerySet' object has no attribute 'model'
```

**Comment by akshey27** [comment]
is there any solution of the problem AttributeError at /api/channel/
'QuerySet' object has no attribute 'model'.. help me to figure it out with this error

**Comment by Vayel** [comment]
@akshey27 can you show the code raising this error?

**Comment by ola-t** [comment]
I am getting this error on `get_object_or_404(MyModel.objects, pk=pk)`

```
/opt/venv/django_py36/lib/python3.6/site-packages/django/shortcuts.py in get_object_or_404

            return queryset.get(*args, **kwargs)

        except AttributeError:

            klass__name = klass.__name__ if isinstance(klass, type) else klass.__class__.__name__

            raise ValueError(

                "First argument to get_object_or_404() must be a Model, Manager, "

                "or QuerySet, not '%s'." % klass__name

            )

        except queryset.model.DoesNotExist:

     ...

            raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)

    def get_list_or_404(klass, *args, **kwargs):

        """

        Uses filter() to return a list of objects, or raise a Http404 exception if

```

**Comment by 0xfib** [comment]
@ola-t, if you try with _get_object_or_404_ to get a model that doesn't exist in database, Http404 exception is raised. 
Read more [here](https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#get-object-or-404).

**Comment by ola-t** [comment]
@0xfib I appreciate your comment but fromt he above `except queryset.model.DoesNotExist:` throw the exception `'QuerySet' object has no attribute 'model'`. It is not reaching the next line `raise Http404...`

**Comment by 0xfib** [comment]
First argument needs to be **MyModel** not _MyModel.objects_
Hope that's the case.

**Comment by ola-t** [comment]
@0xfib get_object_or_404 accept Model, Manager, or QuerySet, see `Exception Value: | First argument to get_object_or_404() must be a Model, Manager, or QuerySet, not 'MyModel'.`

**Comment by SergiiShcherbak** [comment]
I had the same problem, with exception located somewhere in rest_framework/permissions.py/has_permission. The issue was that I initially included `rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly` following the [DRF tutorial](http://www.django-rest-framework.org/). Solved the problem by replacing the permission with `rest_framework.permissions.IsAuthenticated`.

**Comment by GaoXiuya** [comment]
@SergiiShcherbak It's worked.thx.

**Comment by mhbahmani** [comment]
I had the same problem while overriding  GenericViewset update function, i think it was because i want to change an instance that wasn't from django models, though was document (mongdb).
I solved it by implementing function by myself.

**Comment by thaisvergani** [comment]
@SergiiShcherbak  It worked for me thank you SO MUCH i've lost hours on this ❤️❤️

**Comment by nasimuzzaman-nasim** [comment]
> I had the same problem, with exception located somewhere in rest_framework/permissions.py/has_permission. The issue was that I initially included `rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly` following the [DRF tutorial](http://www.django-rest-framework.org/). Solved the problem by replacing the permission with `rest_framework.permissions.IsAuthenticated`.

Truly, you are a lifesaver <3

**Comment by jwerardi** [comment]
We had this problem show up in a slightly different flavor - if you're filtering by `rest_framework.filters`'s `OrderingFilter`, you now need a `ordering_fields` clause within your `ModelViewSet`. Without it, you'll get the traceback in the OP here. 


```
from rest_framework_mongoengine import viewsets
from rest_framework.filters import OrderingFilter

class MyViewSet(viewsets.ModelViewSet):
    filter_backends = [ ... , OrderingFilter, ...]
    ordering_fields = "createdAt" # Now required to include w/ Django 3.x +

```

**Comment by IATF** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jwerardi** [comment]
enjoy your vacation :)
