### ISSUE TITLE
GenericRefrence field not supported yet.

### ISSUE THREAD

**Issue by weiztech** [umutbozkurt/django-rest-framework-mongoengine#97]
i got message not support on genericReference Field.

**Comment by qwiglydee** [comment]
Implemented mapping it into `ReferenceField(read_only=True)`
It will be serialized to `str(objectid)`.

See it in [tests](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/tests/test_3reference.py#L206)

If you need something smarter, like porviding collection in serializing, you'll need to implement some another field, like DBRefField.
