### ISSUE TITLE
has_object_permission does not call in ModelViewSet

### ISSUE THREAD

**Issue by mory0tiki** [umutbozkurt/django-rest-framework-mongoengine#99]
I have a ModelViewSet and I set a custom permission class for it that checks object-level permission but the object-level permission (has_object_permission) never call.

**Comment by qwiglydee** [comment]
Seems like unrelated to DRF-ME.

Please, provide test case, using current trunk and [dev environment](https://github.com/umutbozkurt/django-rest-framework-mongoengine/blob/master/requirements_dev.txt)
